version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs-app
    container_name: nodejs-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production